- name: Configuring nginx server
  hosts: host
  become: yes
  tasks:
  - name: Installing nginx server
    ansible.builtin.package:
      name: httpd
      state: present

  - name: Start service httpd
    ansible.builtin.service:
      name: httpd
      state: started